name: Auto Test

on:
  push:
    paths:
      - 'submissions/**/*.py'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get changed file
      id: info
      run: |
        FILE=$(git diff --name-only HEAD^ HEAD | grep -E '^submissions/.*\.(py|c|cpp)$' | head -1)
        echo "file=$FILE" >> $GITHUB_OUTPUT
        PROB=$(echo "$FILE" | grep -oP 'Q\K[0-9]+')
        echo "prob=$PROB" >> $GITHUB_OUTPUT
    - name: Run judge
      if: steps.info.outputs.file != ''
      run: bash judge.sh ${{ steps.info.outputs.prob }} ${{ steps.info.outputs.file }}
    - name: Commit report
      if: steps.info.outputs.file != ''
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add submissions/
        git diff --quiet || (git commit -m "auto test report" && git push)